version: '3.9'

services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/db:/data/db

  nginx:
    build: ./nginx
    container_name: ms_nginx
    depends_on:
      - store
      - users
    ports:
      - '80:80'
      # - "3000:80"

  rabbitmq: 
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "sachin"
      RABBITMQ_DEFAULT_PASS: "admin1234"
    ports: 
      # AMQP protocol port
      - '5672:5672'
      # MANAGEMENT UI
      - '15672:15672'

  store:
    build: ./store
    container_name: ms_store
    depends_on:
      - mongo
    volumes:
      - ./store:/app/store
    ports:
      - "3004:3000"

  users: 
    build: ./users
    container_name: ms_users
    depends_on:
      - mongo
    volumes:
      - ./users:/app/users
    ports:
      - "3006:3000"

